name: "Delta Checks Routing"

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true

jobs:
  pr-checks:
    name: Governança da Pull Request
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      repository-projects: read
      contents: read

    steps:
      - name: Checkout do código
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Checkout dos scripts globais (.github)
        uses: actions/checkout@v6
        with:
          repository: ${{ github.repository_owner }}/.github
          ref: main
          path: actions-scripts
          persist-credentials: false

      - name: Verificar bypass emergencial
        id: ci-bypass
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python ./actions-scripts/scripts/check_ci_bypass.py

      - name: Validar commits
        if: steps.ci-bypass.outputs.enabled != 'true'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: >-
          python ./actions-scripts/scripts/validate_commits.py
          --base "${{ github.event.pull_request.base.sha }}"
          --head "${{ github.event.pull_request.head.sha }}"

      - name: Validar .gitignore
        if: steps.ci-bypass.outputs.enabled != 'true'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: >-
          python ./actions-scripts/scripts/validate_gitignore.py
          --project ./.gitignore
          --reference ./actions-scripts/.gitignore
          --repository .

      - name: Validar checks da PR
        if: steps.ci-bypass.outputs.enabled != 'true'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          ORG_NAME: ${{ github.repository_owner }}
        run: python ./actions-scripts/scripts/route_checks.py

      - name: Adicionar revisores
        if: steps.ci-bypass.outputs.enabled != 'true'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          PR_BODY: ${{ github.event.pull_request.body }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          ORG_NAME: ${{ github.repository_owner }}
        run: python ./actions-scripts/scripts/route_reviewers.py
